scheming_version: 2
schema_id: tour_config
about: Configuration options for the DOI extension

fields:
  - field_name: ckanext.tour.autoplay
    label: Autoplay
    help_text: If enabled, the tour will start automatically when the page is loaded
    validators: default(false), one_of([true, false])
    preset: select
    required: true
    choices:
      - value: true
        label: Enabled
      - value: false
        label: Disabled

  - field_name: ckanext.tour.default_anchor
    label: Default Anchor
    help_text: The default anchor for the tour to attach to
    validators: default('.breadcrumb .active'), unicode_safe
    required: true

  - field_name: ckanext.tour.collapse_steps
    label: Collapse Steps
    help_text: If enabled, the tour steps will be collapsed on edit/create
    validators: default(true), one_of([true, false])
    preset: select
    required: true
    choices:
      - value: true
        label: Enabled
      - value: false
        label: Disabled
