version: 1
groups:
  - annotation: Admin panel example
    options:
      - key: ckanext.tour.autoplay
        type: bool
        default: false
        description: If enabled, the tour will start automatically
        editable: true

      - key: ckanext.tour.default_anchor
        default: '.breadcrumb .active'
        description: The default anchor for the tour to attach to
        editable: true

      - key: ckanext.tour.collapse_steps
        type: bool
        default: true
        description: If enabled, the tour steps will be collapsed on edit/create
        editable: true
